"""Add User-Podcast relationship

Revision ID: fc122b558360
Revises: 486a2d215ca6
Create Date: 2025-06-13 11:33:33.009094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc122b558360'
down_revision = '486a2d215ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.drop_column('genre')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
